# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: cenkay
  postfix: 0006
  location: westeurope
  environment: prod
  enable_aml_computecluster: true
  enable_aml_secure_workspace: false



  # Azure DevOps
  ado_service_connection_rg: MLOPS-SUBSCON
  ado_service_connection_aml_ws: MLOPS-SUBSCON
  mlops_rglevelcon: InfraRGLevelCon

  # Compute target for pipeline
  training_target: mlops-cenkay-compute
  training_target_sku: STANDARD_D2_V2
  training_target_min_nodes: 0
  training_target_max_nodes: 4
  training_target_tier: dedicated

  tenant_id: "0682471f-451c-40a4-af3c-b81488e7e40a"
  resource_group: rg-cenkay-0006-prod
  aml_workspace: mlw-cenkay-0006-prod
  online-endpoint: mlw-cenkay-0006-oe
  batch-endpoint:  mlw-cenkay-0006-be

